fixes the pipeline

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -35,5 +35,5 @@ jobs:
     - name: Check the test results 
       run: |
         echo "checking the test log:"
-        errors=$(cat log.txt | grep "^Error")
+        errors=$(cat log.txt | grep "^Error" || true)
         if [ -n "$errors" ]; then echo $errors && exit 1; fi
